---
- meta: flush_handlers
- name: temp db user block (mariadb)
  block:
    - name: create temp mariadb user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ temp_user_name }}"
        password: "{{ temp_user_pass }}"
        priv: "*.*:ALL,GRANT"
        state: present
    - name: run nextcloud installation command
      become: yes
      become_user: www-data
      block:
        - name: install nextcloud (mariadb)
          command: "php occ maintenance:install \
                    --admin-user={{ nextcloud_admin_user }} \
                    --admin-pass={{ nextcloud_admin_pass }} \
                    --data-dir={{ nextcloud_data_directory }} \
                    --database=mysql \
                    --database-name=nextcloud \
                    --database-user={{ temp_user_name }} \
                    --database-pass={{ temp_user_pass }}"
          args:
            chdir: /var/www/html/nextcloud
  always:
    - name: remove temp mariadb user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ temp_user_name }}"
        state: absent

# vim: ts=2 sw=2 et
